apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: flask-app-replica-set
spec:
  replicas: 3
  selector:
    matchLabels:
      app-name: flask-app
  template:
    metadata:
      labels:
        app-name: flask-app
    spec:
      containers:
      - name: flask-app
        image: cosminionita/flask-app:1.0.6
