apiVersion: v1
kind: Service
metadata:
 name: flask-app-node-port-svc
spec:
  type: NodePort
  selector:
    app: flask-simple-api
  ports:
  - name: http
    port: 8080
    nodePort: 30100
    targetPort: 8080
    protocol: TCP 
