apiVersion: v1
kind: Service
metadata:
 name: flask-app-headless-svc
spec:
  clusterIP: None
  selector:
    app: flask-simple-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP 
