apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-custom-pv
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/custom/pv