apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-app-ss
spec:
  replicas: 3
  serviceName: "my-app"

  selector:
    matchLabels:
      app: my-app
  
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: busybox
        image: busybox
        command: ['sh', '-c', 'sleep 1000']
        volumeMounts:
        - name: data-volume
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 1Gi